-- DROP TYPE IF EXISTS public.account_type;
/*
CREATE TYPE public.account_type AS ENUM
    ('Client', 'Employee', 'Admin');

ALTER TYPE public.account_type
    OWNER TO cse340;
*/

create table  if not exists public.classification (
classification_id int generated by default as identity,
classification_name character varying not null,
constraint classification_pk primary key (classification_id)
);

create table if not exists public.inventory
(
inv_id integer not null generated by default as identity,
inv_make character varying not null,
inv_model character varying not null,
inv_year character(4) not null,
inv_description text not null,
inv_image character varying not null,
inv_thumbanil character varying not null,
inv_price numeric(9,0) not null,
inv_miles integer not null,
inv_color character varying not null,
classification_id integer not null,
constraint inventory_pkey primary key (inv_id)
);

ALTER TABLE IF EXISTS public.inventory
ADD CONSTRAINT fk_classification FOREIGN KEY (classification_id)
REFERENCES public.classification (classification_id) MATCH SIMPLE
ON UPDATE CASCADE
ON DELETE NO ACTION;



-- Table structure for table account
CREATE TABLE IF NOT EXISTS public.account
(
    account_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    account_firstname character varying NOT NULL,
    account_lastname character varying NOT NULL,
    account_email character varying NOT NULL,
    account_password character varying NOT NULL,
    account_type account_type  DEFAULT 'Client'::account_type,
    CONSTRAINT account_pkey PRIMARY KEY (account_id)
);




